### ISSUE TITLE
Unable to start Home Assistant

### ISSUE THREAD

**Issue by ejonesnospam** [newAM/hisensetv#6]
Currently, home assistant will fail to start if the hisensetv switch or media_player integration is included after the update of the API to 0.1.3 from previous release of 0.0.7.

- Error Message in HA reported of a pip install failure on armv7 device and unable to find 'requirements.txt'

The custom_component can still be used if the manifest.json document is updated to force only version 0.0.7.

**Comment by newAM** [comment]
Sorry about that!  Should be fixed now with `0.1.4`.

I had a weird issue installing it on my system afterwards:
```
AttributeError: type object 'Callable' has no attribute '_abc_registry'
```
I had to `pip uninstall typing` for the install to work; but that seems to be a me problem since this works in docker:

```
FROM ubuntu:20.04
RUN apt update
RUN apt install -y python3 python3-pip
RUN python3 -m pip install hisensetv
```

Can you let me know if this is OK on your system?
